export const products = [
  // ── RAM ──

  // DDR5
  {type:'ram',name:'Corsair Vengeance DDR5-5600 32 Go (2x16 Go)',brand:'Corsair',description:'Kit mémoire DDR5 haute performance avec profil XMP 3.0 pour un overclocking simplifié.',specs:{Type:'DDR5',Fréquence:'5600 MHz',Latence:'CL36','Capacité':'32 Go (2x16 Go)',Profil:'XMP 3.0'},price_ch:89,price_fr:0,release_year:2023,popularity_score:92,available_ch:true,active:true},
  {type:'ram',name:'Corsair Vengeance DDR5-5600 64 Go (2x32 Go)',brand:'Corsair',description:'Kit 64 Go DDR5 idéal pour les stations de travail et le multitâche intensif.',specs:{Type:'DDR5',Fréquence:'5600 MHz',Latence:'CL36','Capacité':'64 Go (2x32 Go)',Profil:'XMP 3.0'},price_ch:169,price_fr:0,release_year:2023,popularity_score:80,available_ch:true,active:true},
  {type:'ram',name:'Corsair Vengeance DDR5-5600 16 Go (2x8 Go)',brand:'Corsair',description:'Kit DDR5 compact et abordable pour les configurations gaming entrée de gamme.',specs:{Type:'DDR5',Fréquence:'5600 MHz',Latence:'CL36','Capacité':'16 Go (2x8 Go)',Profil:'XMP 3.0'},price_ch:52,price_fr:0,release_year:2023,popularity_score:78,available_ch:true,active:true},
  {type:'ram',name:'G.Skill Trident Z5 RGB DDR5-6000 32 Go (2x16 Go)',brand:'G.Skill',description:'Mémoire DDR5 haut de gamme avec éclairage RGB et profil XMP 3.0 optimisé.',specs:{Type:'DDR5',Fréquence:'6000 MHz',Latence:'CL30','Capacité':'32 Go (2x16 Go)',Profil:'XMP 3.0'},price_ch:119,price_fr:0,release_year:2023,popularity_score:93,available_ch:true,active:true},
  {type:'ram',name:'G.Skill Trident Z5 RGB DDR5-6000 64 Go (2x32 Go)',brand:'G.Skill',description:'Kit 64 Go DDR5 premium avec RGB pour les créateurs et power users.',specs:{Type:'DDR5',Fréquence:'6000 MHz',Latence:'CL30','Capacité':'64 Go (2x32 Go)',Profil:'XMP 3.0'},price_ch:219,price_fr:0,release_year:2023,popularity_score:82,available_ch:true,active:true},
  {type:'ram',name:'G.Skill Trident Z5 Neo RGB DDR5-6000 32 Go (2x16 Go)',brand:'G.Skill',description:'Mémoire DDR5 optimisée AMD EXPO pour les plateformes Ryzen AM5.',specs:{Type:'DDR5',Fréquence:'6000 MHz',Latence:'CL30','Capacité':'32 Go (2x16 Go)',Profil:'AMD EXPO'},price_ch:125,price_fr:0,release_year:2023,popularity_score:90,available_ch:true,active:true},
  {type:'ram',name:'G.Skill Flare X5 DDR5-6000 32 Go (2x16 Go)',brand:'G.Skill',description:'Kit DDR5 sobre et performant, conçu spécialement pour les processeurs AMD Ryzen.',specs:{Type:'DDR5',Fréquence:'6000 MHz',Latence:'CL30','Capacité':'32 Go (2x16 Go)',Profil:'AMD EXPO'},price_ch:105,price_fr:0,release_year:2023,popularity_score:85,available_ch:true,active:true},
  {type:'ram',name:'Kingston Fury Beast DDR5-5600 32 Go (2x16 Go)',brand:'Kingston',description:'Mémoire DDR5 fiable avec dissipateur thermique élégant et profil XMP 3.0.',specs:{Type:'DDR5',Fréquence:'5600 MHz',Latence:'CL36','Capacité':'32 Go (2x16 Go)',Profil:'XMP 3.0'},price_ch:85,price_fr:0,release_year:2023,popularity_score:86,available_ch:true,active:true},
  {type:'ram',name:'Kingston Fury Beast DDR5-5600 64 Go (2x32 Go)',brand:'Kingston',description:'Kit 64 Go DDR5 Kingston pour les configurations nécessitant beaucoup de mémoire.',specs:{Type:'DDR5',Fréquence:'5600 MHz',Latence:'CL36','Capacité':'64 Go (2x32 Go)',Profil:'XMP 3.0'},price_ch:165,price_fr:0,release_year:2023,popularity_score:75,available_ch:true,active:true},
  {type:'ram',name:'Kingston Fury Renegade DDR5-6400 32 Go (2x16 Go)',brand:'Kingston',description:'Mémoire DDR5 ultra-rapide pour les enthusiastes et overclockers exigeants.',specs:{Type:'DDR5',Fréquence:'6400 MHz',Latence:'CL32','Capacité':'32 Go (2x16 Go)',Profil:'XMP 3.0'},price_ch:139,price_fr:0,release_year:2023,popularity_score:84,available_ch:true,active:true},
  {type:'ram',name:'TeamGroup T-Force Delta RGB DDR5-6000 32 Go (2x16 Go)',brand:'TeamGroup',description:'Kit DDR5 avec éclairage RGB diffus et excellentes performances en jeu.',specs:{Type:'DDR5',Fréquence:'6000 MHz',Latence:'CL30','Capacité':'32 Go (2x16 Go)',Profil:'XMP 3.0'},price_ch:109,price_fr:0,release_year:2023,popularity_score:79,available_ch:true,active:true},
  {type:'ram',name:'Corsair Dominator Platinum RGB DDR5-6200 32 Go (2x16 Go)',brand:'Corsair',description:'Mémoire DDR5 premium avec éclairage Capellix et design haut de gamme.',specs:{Type:'DDR5',Fréquence:'6200 MHz',Latence:'CL32','Capacité':'32 Go (2x16 Go)',Profil:'XMP 3.0'},price_ch:149,price_fr:0,release_year:2023,popularity_score:83,available_ch:true,active:true},

  // DDR4
  {type:'ram',name:'Corsair Vengeance LPX DDR4-3200 32 Go (2x16 Go)',brand:'Corsair',description:'Kit DDR4 low-profile très populaire, compatible avec la plupart des configurations.',specs:{Type:'DDR4',Fréquence:'3200 MHz',Latence:'CL16','Capacité':'32 Go (2x16 Go)',Profil:'XMP 2.0'},price_ch:62,price_fr:0,release_year:2022,popularity_score:90,available_ch:true,active:true},
  {type:'ram',name:'Corsair Vengeance LPX DDR4-3200 16 Go (2x8 Go)',brand:'Corsair',description:'Kit DDR4 abordable et fiable pour les builds gaming et bureautique.',specs:{Type:'DDR4',Fréquence:'3200 MHz',Latence:'CL16','Capacité':'16 Go (2x8 Go)',Profil:'XMP 2.0'},price_ch:35,price_fr:0,release_year:2022,popularity_score:88,available_ch:true,active:true},
  {type:'ram',name:'Kingston Fury Beast DDR4-3200 32 Go (2x16 Go)',brand:'Kingston',description:'Mémoire DDR4 performante avec dissipateur thermique stylisé.',specs:{Type:'DDR4',Fréquence:'3200 MHz',Latence:'CL16','Capacité':'32 Go (2x16 Go)',Profil:'XMP 2.0'},price_ch:59,price_fr:0,release_year:2022,popularity_score:85,available_ch:true,active:true},
  {type:'ram',name:'Kingston Fury Beast DDR4-3200 16 Go (2x8 Go)',brand:'Kingston',description:'Kit DDR4 16 Go fiable et bon marché pour les configurations standard.',specs:{Type:'DDR4',Fréquence:'3200 MHz',Latence:'CL16','Capacité':'16 Go (2x8 Go)',Profil:'XMP 2.0'},price_ch:33,price_fr:0,release_year:2022,popularity_score:83,available_ch:true,active:true},
  {type:'ram',name:'G.Skill Ripjaws V DDR4-3600 32 Go (2x16 Go)',brand:'G.Skill',description:'Kit DDR4 haute fréquence idéal pour les plateformes AMD Ryzen.',specs:{Type:'DDR4',Fréquence:'3600 MHz',Latence:'CL18','Capacité':'32 Go (2x16 Go)',Profil:'XMP 2.0'},price_ch:69,price_fr:0,release_year:2022,popularity_score:87,available_ch:true,active:true},
  {type:'ram',name:'Crucial Ballistix DDR4-3600 16 Go (2x8 Go)',brand:'Crucial',description:'Mémoire DDR4 avec excellent potentiel d\'overclocking et faible latence.',specs:{Type:'DDR4',Fréquence:'3600 MHz',Latence:'CL16','Capacité':'16 Go (2x8 Go)',Profil:'XMP 2.0'},price_ch:45,price_fr:0,release_year:2022,popularity_score:81,available_ch:true,active:true},

  // ── Stockage ──

  // NVMe Gen5
  {type:'stockage',name:'Samsung 990 EVO Plus 1 To',brand:'Samsung',description:'SSD NVMe Gen5 Samsung offrant des vitesses exceptionnelles pour le gaming et la création.',specs:{'Capacité':'1 To',Interface:'NVMe PCIe 5.0 x4','Lecture séq.':'10 000 Mo/s','Écriture séq.':'8 000 Mo/s','Form factor':'M.2 2280'},price_ch:119,price_fr:0,release_year:2025,popularity_score:90,available_ch:true,active:true},
  {type:'stockage',name:'Samsung 990 EVO Plus 2 To',brand:'Samsung',description:'SSD NVMe Gen5 grande capacité pour stocker jeux et projets créatifs.',specs:{'Capacité':'2 To',Interface:'NVMe PCIe 5.0 x4','Lecture séq.':'10 000 Mo/s','Écriture séq.':'8 000 Mo/s','Form factor':'M.2 2280'},price_ch:189,price_fr:0,release_year:2025,popularity_score:87,available_ch:true,active:true},
  {type:'stockage',name:'Crucial T700 1 To',brand:'Crucial',description:'SSD NVMe Gen5 parmi les plus rapides du marché avec dissipateur inclus.',specs:{'Capacité':'1 To',Interface:'NVMe PCIe 5.0 x4','Lecture séq.':'12 400 Mo/s','Écriture séq.':'11 800 Mo/s','Form factor':'M.2 2280'},price_ch:139,price_fr:0,release_year:2024,popularity_score:88,available_ch:true,active:true},
  {type:'stockage',name:'Crucial T700 2 To',brand:'Crucial',description:'SSD Gen5 ultra-rapide 2 To pour les professionnels et enthousiastes.',specs:{'Capacité':'2 To',Interface:'NVMe PCIe 5.0 x4','Lecture séq.':'12 400 Mo/s','Écriture séq.':'11 800 Mo/s','Form factor':'M.2 2280'},price_ch:239,price_fr:0,release_year:2024,popularity_score:83,available_ch:true,active:true},
  {type:'stockage',name:'WD Black SN850X 1 To',brand:'Western Digital',description:'SSD NVMe Gen4 phare de WD, excellent pour le gaming et les charges lourdes.',specs:{'Capacité':'1 To',Interface:'NVMe PCIe 4.0 x4','Lecture séq.':'7 300 Mo/s','Écriture séq.':'6 300 Mo/s','Form factor':'M.2 2280'},price_ch:89,price_fr:0,release_year:2023,popularity_score:91,available_ch:true,active:true},
  {type:'stockage',name:'WD Black SN850X 2 To',brand:'Western Digital',description:'Version 2 To du SSD gaming référence de Western Digital.',specs:{'Capacité':'2 To',Interface:'NVMe PCIe 4.0 x4','Lecture séq.':'7 300 Mo/s','Écriture séq.':'6 600 Mo/s','Form factor':'M.2 2280'},price_ch:149,price_fr:0,release_year:2023,popularity_score:89,available_ch:true,active:true},
  {type:'stockage',name:'Corsair MP700 1 To',brand:'Corsair',description:'SSD NVMe Gen5 Corsair avec des débits séquentiels impressionnants.',specs:{'Capacité':'1 To',Interface:'NVMe PCIe 5.0 x4','Lecture séq.':'9 500 Mo/s','Écriture séq.':'8 500 Mo/s','Form factor':'M.2 2280'},price_ch:129,price_fr:0,release_year:2024,popularity_score:82,available_ch:true,active:true},
  {type:'stockage',name:'Corsair MP700 2 To',brand:'Corsair',description:'SSD Gen5 2 To Corsair pour les configurations exigeantes.',specs:{'Capacité':'2 To',Interface:'NVMe PCIe 5.0 x4','Lecture séq.':'10 000 Mo/s','Écriture séq.':'9 500 Mo/s','Form factor':'M.2 2280'},price_ch:209,price_fr:0,release_year:2024,popularity_score:79,available_ch:true,active:true},

  // NVMe Gen4
  {type:'stockage',name:'Samsung 990 Pro 1 To',brand:'Samsung',description:'SSD NVMe Gen4 premium avec des performances de pointe et une excellente endurance.',specs:{'Capacité':'1 To',Interface:'NVMe PCIe 4.0 x4','Lecture séq.':'7 450 Mo/s','Écriture séq.':'6 900 Mo/s','Form factor':'M.2 2280'},price_ch:95,price_fr:0,release_year:2023,popularity_score:93,available_ch:true,active:true},
  {type:'stockage',name:'Samsung 990 Pro 2 To',brand:'Samsung',description:'Version 2 To du SSD Gen4 référence de Samsung.',specs:{'Capacité':'2 To',Interface:'NVMe PCIe 4.0 x4','Lecture séq.':'7 450 Mo/s','Écriture séq.':'6 900 Mo/s','Form factor':'M.2 2280'},price_ch:155,price_fr:0,release_year:2023,popularity_score:90,available_ch:true,active:true},
  {type:'stockage',name:'Samsung 980 Pro 1 To',brand:'Samsung',description:'SSD NVMe Gen4 éprouvé avec un excellent rapport performances/prix.',specs:{'Capacité':'1 To',Interface:'NVMe PCIe 4.0 x4','Lecture séq.':'7 000 Mo/s','Écriture séq.':'5 000 Mo/s','Form factor':'M.2 2280'},price_ch:79,price_fr:0,release_year:2022,popularity_score:85,available_ch:true,active:true},
  {type:'stockage',name:'Crucial T500 1 To',brand:'Crucial',description:'SSD NVMe Gen4 rapide avec un bon rapport qualité-prix.',specs:{'Capacité':'1 To',Interface:'NVMe PCIe 4.0 x4','Lecture séq.':'7 300 Mo/s','Écriture séq.':'6 800 Mo/s','Form factor':'M.2 2280'},price_ch:82,price_fr:0,release_year:2024,popularity_score:86,available_ch:true,active:true},
  {type:'stockage',name:'Crucial T500 2 To',brand:'Crucial',description:'SSD Gen4 2 To Crucial pour le stockage performant à prix raisonnable.',specs:{'Capacité':'2 To',Interface:'NVMe PCIe 4.0 x4','Lecture séq.':'7 400 Mo/s','Écriture séq.':'7 000 Mo/s','Form factor':'M.2 2280'},price_ch:139,price_fr:0,release_year:2024,popularity_score:84,available_ch:true,active:true},
  {type:'stockage',name:'Kingston Fury Renegade 1 To',brand:'Kingston',description:'SSD NVMe Gen4 haute performance avec dissipateur en aluminium.',specs:{'Capacité':'1 To',Interface:'NVMe PCIe 4.0 x4','Lecture séq.':'7 300 Mo/s','Écriture séq.':'7 000 Mo/s','Form factor':'M.2 2280'},price_ch:89,price_fr:0,release_year:2023,popularity_score:83,available_ch:true,active:true},
  {type:'stockage',name:'Kingston Fury Renegade 2 To',brand:'Kingston',description:'SSD Gen4 2 To Kingston pour les gamers et créateurs de contenu.',specs:{'Capacité':'2 To',Interface:'NVMe PCIe 4.0 x4','Lecture séq.':'7 300 Mo/s','Écriture séq.':'7 000 Mo/s','Form factor':'M.2 2280'},price_ch:155,price_fr:0,release_year:2023,popularity_score:80,available_ch:true,active:true},
  {type:'stockage',name:'Seagate FireCuda 530 1 To',brand:'Seagate',description:'SSD NVMe Gen4 avec endurance élevée et performances gaming optimales.',specs:{'Capacité':'1 To',Interface:'NVMe PCIe 4.0 x4','Lecture séq.':'7 300 Mo/s','Écriture séq.':'6 000 Mo/s','Form factor':'M.2 2280'},price_ch:92,price_fr:0,release_year:2023,popularity_score:82,available_ch:true,active:true},
  {type:'stockage',name:'Seagate FireCuda 530 2 To',brand:'Seagate',description:'SSD Gen4 2 To Seagate avec 2 550 TBW d\'endurance.',specs:{'Capacité':'2 To',Interface:'NVMe PCIe 4.0 x4','Lecture séq.':'7 300 Mo/s','Écriture séq.':'6 900 Mo/s','Form factor':'M.2 2280'},price_ch:159,price_fr:0,release_year:2023,popularity_score:79,available_ch:true,active:true},

  // SATA
  {type:'stockage',name:'Samsung 870 EVO 1 To',brand:'Samsung',description:'SSD SATA de référence avec une fiabilité et des performances éprouvées.',specs:{'Capacité':'1 To',Interface:'SATA III 6 Gb/s','Lecture séq.':'560 Mo/s','Écriture séq.':'530 Mo/s','Form factor':'2.5"'},price_ch:69,price_fr:0,release_year:2022,popularity_score:88,available_ch:true,active:true},
  {type:'stockage',name:'Samsung 870 EVO 2 To',brand:'Samsung',description:'SSD SATA grande capacité, idéal comme stockage secondaire rapide.',specs:{'Capacité':'2 To',Interface:'SATA III 6 Gb/s','Lecture séq.':'560 Mo/s','Écriture séq.':'530 Mo/s','Form factor':'2.5"'},price_ch:119,price_fr:0,release_year:2022,popularity_score:84,available_ch:true,active:true},
  {type:'stockage',name:'Crucial MX500 1 To',brand:'Crucial',description:'SSD SATA fiable et abordable pour les mises à niveau et builds économiques.',specs:{'Capacité':'1 To',Interface:'SATA III 6 Gb/s','Lecture séq.':'560 Mo/s','Écriture séq.':'510 Mo/s','Form factor':'2.5"'},price_ch:59,price_fr:0,release_year:2022,popularity_score:86,available_ch:true,active:true},

  // ── Cartes mères ──

  // AM5
  {type:'carte_mere',name:'ASUS ROG STRIX X670E-E Gaming WiFi',brand:'ASUS',description:'Carte mère AM5 haut de gamme avec connectivité complète et VRM robustes.',specs:{Socket:'AM5',Chipset:'X670E',Format:'ATX','RAM max':'128 Go DDR5',WiFi:'WiFi 6E','Slots M.2':4},socket:'AM5',chipset:'X670E',form_factor:'ATX',price_ch:399,price_fr:0,release_year:2023,popularity_score:90,available_ch:true,active:true},
  {type:'carte_mere',name:'ASUS ROG STRIX B650-A Gaming WiFi',brand:'ASUS',description:'Carte mère AM5 milieu de gamme avec design blanc et bonnes fonctionnalités.',specs:{Socket:'AM5',Chipset:'B650',Format:'ATX','RAM max':'128 Go DDR5',WiFi:'WiFi 6E','Slots M.2':3},socket:'AM5',chipset:'B650',form_factor:'ATX',price_ch:249,price_fr:0,release_year:2023,popularity_score:88,available_ch:true,active:true},
  {type:'carte_mere',name:'ASUS TUF Gaming B650-Plus WiFi',brand:'ASUS',description:'Carte mère AM5 robuste et fiable avec un excellent rapport qualité-prix.',specs:{Socket:'AM5',Chipset:'B650',Format:'ATX','RAM max':'128 Go DDR5',WiFi:'WiFi 6','Slots M.2':3},socket:'AM5',chipset:'B650',form_factor:'ATX',price_ch:199,price_fr:0,release_year:2023,popularity_score:91,available_ch:true,active:true},
  {type:'carte_mere',name:'ASUS ProArt X670E-Creator WiFi',brand:'ASUS',description:'Carte mère AM5 orientée création avec Thunderbolt 4 et 10G LAN.',specs:{Socket:'AM5',Chipset:'X670E',Format:'ATX','RAM max':'128 Go DDR5',WiFi:'WiFi 6E','Slots M.2':4},socket:'AM5',chipset:'X670E',form_factor:'ATX',price_ch:449,price_fr:0,release_year:2023,popularity_score:78,available_ch:true,active:true},
  {type:'carte_mere',name:'MSI MAG B650 Tomahawk WiFi',brand:'MSI',description:'Carte mère AM5 polyvalente avec VRM solides et connectique généreuse.',specs:{Socket:'AM5',Chipset:'B650',Format:'ATX','RAM max':'128 Go DDR5',WiFi:'WiFi 6E','Slots M.2':3},socket:'AM5',chipset:'B650',form_factor:'ATX',price_ch:219,price_fr:0,release_year:2023,popularity_score:89,available_ch:true,active:true},
  {type:'carte_mere',name:'MSI MPG X670E Carbon WiFi',brand:'MSI',description:'Carte mère AM5 premium avec design carbon et fonctionnalités enthousiastes.',specs:{Socket:'AM5',Chipset:'X670E',Format:'ATX','RAM max':'128 Go DDR5',WiFi:'WiFi 6E','Slots M.2':4},socket:'AM5',chipset:'X670E',form_factor:'ATX',price_ch:389,price_fr:0,release_year:2023,popularity_score:84,available_ch:true,active:true},
  {type:'carte_mere',name:'Gigabyte B650 AORUS Elite AX',brand:'Gigabyte',description:'Carte mère AM5 équilibrée avec WiFi 6E et audio haute qualité.',specs:{Socket:'AM5',Chipset:'B650',Format:'ATX','RAM max':'128 Go DDR5',WiFi:'WiFi 6E','Slots M.2':3},socket:'AM5',chipset:'B650',form_factor:'ATX',price_ch:209,price_fr:0,release_year:2023,popularity_score:86,available_ch:true,active:true},
  {type:'carte_mere',name:'Gigabyte X670E AORUS Master',brand:'Gigabyte',description:'Carte mère AM5 enthusiaste avec VRM 16+2+2 et connectivité haut de gamme.',specs:{Socket:'AM5',Chipset:'X670E',Format:'ATX','RAM max':'128 Go DDR5',WiFi:'WiFi 6E','Slots M.2':4},socket:'AM5',chipset:'X670E',form_factor:'ATX',price_ch:429,price_fr:0,release_year:2023,popularity_score:82,available_ch:true,active:true},
  {type:'carte_mere',name:'ASRock B650M Pro RS WiFi',brand:'ASRock',description:'Carte mère Micro-ATX AM5 compacte et abordable avec WiFi intégré.',specs:{Socket:'AM5',Chipset:'B650',Format:'Micro-ATX','RAM max':'128 Go DDR5',WiFi:'WiFi 6E','Slots M.2':2},socket:'AM5',chipset:'B650',form_factor:'Micro-ATX',price_ch:159,price_fr:0,release_year:2023,popularity_score:80,available_ch:true,active:true},

  // LGA1700
  {type:'carte_mere',name:'ASUS ROG STRIX Z790-E Gaming WiFi',brand:'ASUS',description:'Carte mère LGA1700 haut de gamme avec VRM puissants et WiFi 6E.',specs:{Socket:'LGA1700',Chipset:'Z790',Format:'ATX','RAM max':'128 Go DDR5',WiFi:'WiFi 6E','Slots M.2':5},socket:'LGA1700',chipset:'Z790',form_factor:'ATX',price_ch:389,price_fr:0,release_year:2023,popularity_score:89,available_ch:true,active:true},
  {type:'carte_mere',name:'ASUS TUF Gaming B760-Plus WiFi',brand:'ASUS',description:'Carte mère LGA1700 fiable pour les builds Intel milieu de gamme.',specs:{Socket:'LGA1700',Chipset:'B760',Format:'ATX','RAM max':'128 Go DDR5',WiFi:'WiFi 6','Slots M.2':3},socket:'LGA1700',chipset:'B760',form_factor:'ATX',price_ch:179,price_fr:0,release_year:2023,popularity_score:87,available_ch:true,active:true},
  {type:'carte_mere',name:'ASUS ROG Maximus Z790 Hero',brand:'ASUS',description:'Carte mère Intel flagship avec fonctionnalités premium et overclocking avancé.',specs:{Socket:'LGA1700',Chipset:'Z790',Format:'ATX','RAM max':'128 Go DDR5',WiFi:'WiFi 6E','Slots M.2':5},socket:'LGA1700',chipset:'Z790',form_factor:'ATX',price_ch:549,price_fr:0,release_year:2023,popularity_score:80,available_ch:true,active:true},
  {type:'carte_mere',name:'MSI MAG B760 Tomahawk WiFi',brand:'MSI',description:'Carte mère LGA1700 polyvalente avec bon rapport qualité-prix.',specs:{Socket:'LGA1700',Chipset:'B760',Format:'ATX','RAM max':'128 Go DDR5',WiFi:'WiFi 6E','Slots M.2':3},socket:'LGA1700',chipset:'B760',form_factor:'ATX',price_ch:189,price_fr:0,release_year:2023,popularity_score:86,available_ch:true,active:true},
  {type:'carte_mere',name:'MSI MPG Z790 Edge WiFi',brand:'MSI',description:'Carte mère Z790 performante pour le gaming et l\'overclocking modéré.',specs:{Socket:'LGA1700',Chipset:'Z790',Format:'ATX','RAM max':'128 Go DDR5',WiFi:'WiFi 6E','Slots M.2':4},socket:'LGA1700',chipset:'Z790',form_factor:'ATX',price_ch:329,price_fr:0,release_year:2023,popularity_score:83,available_ch:true,active:true},
  {type:'carte_mere',name:'Gigabyte Z790 AORUS Elite AX',brand:'Gigabyte',description:'Carte mère Z790 équilibrée avec WiFi 6E et audio premium.',specs:{Socket:'LGA1700',Chipset:'Z790',Format:'ATX','RAM max':'128 Go DDR5',WiFi:'WiFi 6E','Slots M.2':4},socket:'LGA1700',chipset:'Z790',form_factor:'ATX',price_ch:299,price_fr:0,release_year:2023,popularity_score:84,available_ch:true,active:true},
  {type:'carte_mere',name:'Gigabyte B760 AORUS Elite AX',brand:'Gigabyte',description:'Carte mère B760 abordable avec WiFi et fonctionnalités essentielles.',specs:{Socket:'LGA1700',Chipset:'B760',Format:'ATX','RAM max':'128 Go DDR5',WiFi:'WiFi 6E','Slots M.2':3},socket:'LGA1700',chipset:'B760',form_factor:'ATX',price_ch:179,price_fr:0,release_year:2023,popularity_score:82,available_ch:true,active:true},

  // LGA1851 (Arrow Lake)
  {type:'carte_mere',name:'ASUS ROG STRIX Z890-E Gaming WiFi',brand:'ASUS',description:'Carte mère LGA1851 haut de gamme pour les processeurs Intel Arrow Lake.',specs:{Socket:'LGA1851',Chipset:'Z890',Format:'ATX','RAM max':'192 Go DDR5',WiFi:'WiFi 7','Slots M.2':5},socket:'LGA1851',chipset:'Z890',form_factor:'ATX',price_ch:449,price_fr:0,release_year:2025,popularity_score:88,available_ch:true,active:true},
  {type:'carte_mere',name:'ASUS TUF Gaming Z890-Plus WiFi',brand:'ASUS',description:'Carte mère Z890 robuste et abordable pour Arrow Lake.',specs:{Socket:'LGA1851',Chipset:'Z890',Format:'ATX','RAM max':'192 Go DDR5',WiFi:'WiFi 7','Slots M.2':4},socket:'LGA1851',chipset:'Z890',form_factor:'ATX',price_ch:299,price_fr:0,release_year:2025,popularity_score:86,available_ch:true,active:true},
  {type:'carte_mere',name:'MSI MAG Z890 Tomahawk WiFi',brand:'MSI',description:'Carte mère Z890 polyvalente avec VRM solides et WiFi 7.',specs:{Socket:'LGA1851',Chipset:'Z890',Format:'ATX','RAM max':'192 Go DDR5',WiFi:'WiFi 7','Slots M.2':4},socket:'LGA1851',chipset:'Z890',form_factor:'ATX',price_ch:309,price_fr:0,release_year:2025,popularity_score:87,available_ch:true,active:true},
  {type:'carte_mere',name:'MSI MPG Z890 Carbon WiFi',brand:'MSI',description:'Carte mère Z890 premium avec design carbon et connectique complète.',specs:{Socket:'LGA1851',Chipset:'Z890',Format:'ATX','RAM max':'192 Go DDR5',WiFi:'WiFi 7','Slots M.2':5},socket:'LGA1851',chipset:'Z890',form_factor:'ATX',price_ch:429,price_fr:0,release_year:2025,popularity_score:83,available_ch:true,active:true},
  {type:'carte_mere',name:'Gigabyte Z890 AORUS Elite WiFi7',brand:'Gigabyte',description:'Carte mère Z890 équilibrée avec WiFi 7 et support DDR5.',specs:{Socket:'LGA1851',Chipset:'Z890',Format:'ATX','RAM max':'192 Go DDR5',WiFi:'WiFi 7','Slots M.2':4},socket:'LGA1851',chipset:'Z890',form_factor:'ATX',price_ch:289,price_fr:0,release_year:2025,popularity_score:85,available_ch:true,active:true},

  // AM4
  {type:'carte_mere',name:'ASUS TUF Gaming B550-Plus WiFi II',brand:'ASUS',description:'Carte mère AM4 fiable et populaire pour les builds Ryzen 5000.',specs:{Socket:'AM4',Chipset:'B550',Format:'ATX','RAM max':'128 Go DDR4',WiFi:'WiFi 6','Slots M.2':2},socket:'AM4',chipset:'B550',form_factor:'ATX',price_ch:149,price_fr:0,release_year:2022,popularity_score:85,available_ch:true,active:true},
  {type:'carte_mere',name:'MSI MAG B550 Tomahawk',brand:'MSI',description:'Carte mère AM4 robuste avec VRM excellents pour les Ryzen 5000.',specs:{Socket:'AM4',Chipset:'B550',Format:'ATX','RAM max':'128 Go DDR4',WiFi:'Non','Slots M.2':2},socket:'AM4',chipset:'B550',form_factor:'ATX',price_ch:139,price_fr:0,release_year:2022,popularity_score:84,available_ch:true,active:true},
  {type:'carte_mere',name:'Gigabyte B550 AORUS Pro V2',brand:'Gigabyte',description:'Carte mère AM4 complète avec audio premium et réseau 2.5G.',specs:{Socket:'AM4',Chipset:'B550',Format:'ATX','RAM max':'128 Go DDR4',WiFi:'Non','Slots M.2':2},socket:'AM4',chipset:'B550',form_factor:'ATX',price_ch:135,price_fr:0,release_year:2022,popularity_score:81,available_ch:true,active:true},
];
